=== skay44/sample-website-for-University/src/web/static/XML/schemat.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="produkcjaMuzyki" type="produkcjaMuzykiType"/>
  
  <xs:complexType name="produkcjaMuzykiType">
    <xs:sequence>
      <xs:element name="elektroniczne" type="elektroniczneType"/>
      <xs:element name="fizyczne" type="fizyczneType"/>
      <xs:element name="teoria" type="teoriaType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="elektroniczneType">
    <xs:sequence>
      <xs:element name="DAWs" type="DAWsType"/>
      <xs:element name="pluginy" type="pluginyType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DAWsType">
    <xs:sequence>
      <xs:element name="opis" type="długiTekst" minOccurs="0" maxOccurs="1"></xs:element>
      <xs:element name="DAW" type="DAWType" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DAWType">
    <xs:sequence>
      <xs:choice>
        <xs:element name="cena" type="cenaType">
        </xs:element>
        <xs:sequence>
          <xs:group ref="ceny_przedział"/>
          <xs:element name="przewidywana">
            <xs:simpleType>
              <xs:union memberTypes="rozmiar_opisowy którkiZmiennoprzecinkowy" />
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:choice>
      <xs:element name="wydawca" type="wydawcaType"/>
    </xs:sequence>
    <xs:attribute ref="nazwa"/>
  </xs:complexType>
  
  <xs:complexType name="pluginyType">
    <xs:sequence>
      <xs:element name="opis" type="długiTekst" minOccurs="0" maxOccurs="1"></xs:element>
      <xs:element name="plugin" maxOccurs="unbounded">
        <xs:complexType>
          <xs:complexContent>
            <xs:extension base="DAWType">
              <xs:sequence>
                <xs:element name="dzialanie">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:choice maxOccurs="unbounded">
                        <xs:element name="synteza" type="krótkiTekst" />
                        <xs:element name="efekt" type="krótkiTekst" />
                      </xs:choice>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="obraz" minOccurs="0" maxOccurs="1">
                  <xs:complexType>
                    <xs:attribute name="src">
                      <xs:simpleType>
                        <xs:restriction base="krótkiTekst">
                          <xs:pattern value="graphics/.*.png"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
              <xs:attribute name="typ">
                <xs:simpleType>
                  <xs:restriction base="krótkiTekst">
                    <xs:enumeration value="efekt"/>
                    <xs:enumeration value="generujacy"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:attribute>
            </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fizyczneType">
    <xs:sequence>
      <xs:element name="kontrolery">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="kontroler" maxOccurs="unbounded" type="krótkiTekst"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="monitoryStudyjne">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="monitor" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="producent" type="krótkiTekst"/>
                </xs:sequence>
                <xs:attribute ref="nazwa"/>
                <xs:attribute name="wersja" default="1">
                  <xs:simpleType>
                    <xs:union memberTypes="krótkaLiczba zbiórZnaków"/>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="wzmocnienie" type="wzmocnienieType">
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="teoriaType">
    <xs:sequence>
      <xs:element name="gatunki">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="gatunek" maxOccurs="unbounded">
              <xs:complexType>
                <xs:all>
                  <xs:element name="opis" type="długiTekst"/>
                  <xs:element ref="artysci"/>
                </xs:all>
                <xs:attribute ref="nazwa"/>
                <xs:attribute name="taneczny">
                  <xs:simpleType>
                    <xs:restriction base="krótkiTekst">
                      <xs:enumeration value="tak"></xs:enumeration>
                      <xs:enumeration value="nie"></xs:enumeration>
                      <xs:enumeration value="nieokreslone"></xs:enumeration>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="artysci">
    <xs:simpleType>
      <xs:restriction base="stringList">
        <xs:minLength value="1"/>
        <xs:maxLength value="5"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:simpleType name="stringList">
    <xs:list itemType="oneString"></xs:list>
  </xs:simpleType>
  
  <xs:simpleType name="oneString">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^\s]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:group name="ceny_przedział">
    <xs:sequence>
      <xs:element name="minCena" type="cenaType"/>
      <xs:element name="maxCena" type="cenaType"/>
    </xs:sequence>
  </xs:group>


  <xs:complexType name="cenaType">
    <xs:simpleContent>
      <xs:extension base="którkiZmiennoprzecinkowy">
        <xs:attribute name="waluta" type="xs:string" default="zł" use="optional"></xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="rozmiar_opisowy">
    <xs:restriction base="krótkiTekst">
      <xs:enumeration value="dół"/>
      <xs:enumeration value="średnia"/>
      <xs:enumeration value="góra"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="wydawcaType">
    <xs:simpleContent>
      <xs:extension base="krótkiTekst">
        <xs:attribute ref="link"></xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="zbiórZnaków">
    <xs:restriction base="xs:string">
      <xs:maxLength value="5"></xs:maxLength>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="krótkiTekst">
    <xs:restriction base="xs:string">
      <xs:minLength value="2"/>
      <xs:maxLength value="300"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="długiTekst">
    <xs:restriction base="xs:string">
      <xs:minLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="którkiZmiennoprzecinkowy">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="krótkaLiczba">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="linkType">
    <xs:restriction base="xs:anyURI">
      <xs:minLength value="5"/>
      <xs:maxLength value="300"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="wzmocnienieType">
    <xs:restriction base="krótkiTekst">
      <xs:enumeration value="aktywny"/>
      <xs:enumeration value="pasywny"/>
    </xs:restriction>
  </xs:simpleType>
  

  <xs:attribute name="nazwa" type="xs:string"/>
  <xs:attribute name="link" type="linkType"/>
</xs:schema>

=== skay44/sample-website-for-University/src/web/static/XML/data.xml
<?xml version="1.0" encoding="utf-8"?>

<produkcjaMuzyki xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemat.xsd">
  <elektroniczne>
    <DAWs>
      <opis>
        Daw, ang. digital audio interface, po polsku cyfrowa stacja robocza jest to program komputerowy przeznaczony do pracy z dźwiękiem, bardzo często wykorzystywany przy współczenej produkcji muzyki. Ich celem jest zastąpienie pełnowymiarowych konsol znajdujących się w studiach nagraniowych, tak aby większość obróbki dźwięku następowała na komputerze. Jest to rozwiązanie znacznie tańsze i wygodniejsze, a przede wszystkim bardziej dostępne dla ludzi pragnących zając się produkcją muzyki w sposób hobbistyczny.
      </opis>
      <DAW nazwa="FL Studio">
        <minCena waluta="zł">
          349.00
        </minCena>
        <maxCena waluta="zł">
          2249.00
        </maxCena>
        <przewidywana>średnia</przewidywana>
        <wydawca link="https://www.image-line.com/">
          Image line
        </wydawca>
      </DAW>
      
      <DAW nazwa="Ableton Live">
        <minCena waluta="eur">
          79.00
        </minCena>
        <maxCena waluta="eur">
          599.00
        </maxCena>
        <przewidywana>200.00</przewidywana>
        <wydawca link="https://www.ableton.com/">
          Ableton
        </wydawca>
      </DAW>
      
      <DAW nazwa="Logic Pro">
        <cena waluta="usd">
          199.99
        </cena>
        <wydawca link="https://www.apple.com/">
          Apple
        </wydawca>
      </DAW>
      
      <DAW nazwa="Cubase">
        <minCena waluta="zł">
          469.76
        </minCena>
        <maxCena waluta="zł">
          2720.16
        </maxCena>
        <przewidywana>góra</przewidywana>
        <wydawca link="https://www.steinberg.net/">
          Steinberg Media Technologies
        </wydawca>
      </DAW>
      
      <DAW nazwa="GarageBand">
        <cena>
          0
        </cena>
        <wydawca link="https://www.apple.com/">
          Apple
        </wydawca>
      </DAW>
    </DAWs>
    
    
    <pluginy>
      <opis>
        Pluginy, pluginy VST (ang. Virtual Studio Technology), czyli podprogramy otwierane w środowisku zapewnianym przez DAW, których celem jest tworzenie lub modyfikowanie dźwięku a nawet więcej. Pluginy rozróżniamy przede wszystkim na generujące i nakładające efekty, zazwyczaj DAW wyróżnia osobne miejsca do załączena dla obu typów.
      </opis>
      <plugin nazwa="3x OSC" typ="generujacy">
        <cena>
          0
        </cena>
        <wydawca link="https://www.image-line.com/">
          Image line
        </wydawca>
        <dzialanie>
          <synteza>
            oscylator
          </synteza>
          <synteza>
            synteza AM
          </synteza>
          <efekt>
            obwiednia
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(1).png"/>
      </plugin>

      <plugin nazwa="Serum" typ="generujacy">
        <cena waluta="usd">
          189.00
        </cena>
        <wydawca link="https://xferrecords.com/">
          Xfer
        </wydawca>
        <dzialanie>
          <synteza>
            oscylator
          </synteza>
          <synteza>
            synteza AM
          </synteza>
          <synteza>
            synteza tablicowa
          </synteza>
          <synteza>
            sampler
          </synteza>
          <efekt>
            obwiednia
          </efekt>
          <efekt>
            korektor
          </efekt>
          <efekt>
            nasycenie
          </efekt>
          <efekt>
            echo
          </efekt>
          <efekt>
            pogłos
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(2).png"/>
      </plugin>

      <plugin nazwa="Ample Guitar" typ="generujacy">
        <cena>
          0
        </cena>
        <wydawca link="https://www.amplesound.net/en/index.asp">
          Ample Sound
        </wydawca>
        <dzialanie>
          <synteza>
            sampler
          </synteza>
        </dzialanie>
        <obraz src="graphics/fimg(3).png"/>
      </plugin>

      <plugin nazwa="BBC Symphony Orchestra" typ="generujacy">
        <cena waluta="eur">
          599.00
        </cena>
        <wydawca link="https://www.spitfireaudio.com/">
          Spitfire Audio
        </wydawca>
        <dzialanie>
          <synteza>
            sampler
          </synteza>
        </dzialanie>
        <obraz src="graphics/fimg(4).png"/>
      </plugin>

      <plugin nazwa="Kick 2" typ="generujacy">
        <cena waluta="gbp">
          29.97
        </cena>
        <wydawca link="https://www.sonicacademy.com/">
          Sonic Academy
        </wydawca>
        <dzialanie>
          <synteza>
            oscylator
          </synteza>
          <synteza>
            sampler
          </synteza>
          <efekt>
            nasycenie
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(5).png"/>
      </plugin>

      <plugin nazwa="Fruity Parametric EQ 2" typ="efekt">
        <cena>
          0
        </cena>
        <wydawca link="https://www.image-line.com/">
          Image Line
        </wydawca>
        <dzialanie>
          <efekt>
            korektor
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(6).png"/>
      </plugin>

      <plugin nazwa="Fruity Delay 3" typ="efekt">
        <cena>
          0
        </cena>
        <wydawca link="https://www.image-line.com/">
          Image Line
        </wydawca>
        <dzialanie>
          <efekt>
            pogłos
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(7).png"/>
      </plugin>

      <plugin nazwa="Fruity Reeverb 2" typ="efekt">
        <cena>
          0
        </cena>
        <wydawca link="https://www.image-line.com/">
          Image Line
        </wydawca>
        <dzialanie>
          <efekt>
            echo
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(8).png"/>
      </plugin>

      <plugin nazwa="Guitar Rig 6" typ="efekt">
        <cena waluta="eur">
          199.00
        </cena>
        <wydawca link="https://www.native-instruments.com/en/">
          Native Instruments
        </wydawca>
        <dzialanie>
          <efekt>
            nasycenie
          </efekt>
          <efekt>
            korektor
          </efekt>
          <efekt>
            kompresor
          </efekt>
          <efekt>
            pogłos
          </efekt>
          <efekt>
            echo
          </efekt>
          <efekt>
            filtr
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(9).png"/>
      </plugin>

      <plugin nazwa="iZotope Vinyl" typ="efekt">
        <cena>
          0
        </cena>
        <wydawca link="https://www.izotope.com/">
          iZotope
        </wydawca>
        <dzialanie>
          <synteza>
            sampler
          </synteza>
          <efekt>
            filtr
          </efekt>
        </dzialanie>
        <obraz src="graphics/fimg(10).png"/>
      </plugin>
    </pluginy>
  </elektroniczne>
  
  
  <fizyczne>
    <kontrolery>
      <kontroler>
        Klawisze MIDI
      </kontroler>
      <kontroler>
        Drumpad MIDI
      </kontroler>
      <kontroler>
        Gitara Elektryczna
      </kontroler>
      <kontroler>
        Pianino Elektryczne
      </kontroler>
    </kontrolery>
    <monitoryStudyjne>
      <monitor nazwa="HS" wersja="8" wzmocnienie="aktywny">
        <producent>
          Yamaha
        </producent>
      </monitor>
      <monitor nazwa="SCM" wersja="12" wzmocnienie="pasywny">
        <producent>
          ATC
        </producent>
      </monitor>
      <monitor nazwa="HS" wersja="7" wzmocnienie="aktywny">
        <producent>
          Yamaha
        </producent>
      </monitor>
      <monitor nazwa="Super Sound" wersja="5C" wzmocnienie="pasywny">
        <producent>
          Auratone
        </producent>
      </monitor>
    </monitoryStudyjne>
  </fizyczne>

  <teoria>
    <gatunki>
      <gatunek taneczny="tak" nazwa="House">
        <opis>
          Jeden z najpopularniejszych gatunków muzyki, rywalizujący swoją poularnością z rockem, hip-hopem a takż szeroko pojętym popem. Charakteryzuje się rytmem "4 on the floor" w którym każdy beat jest akcentowany bębnem basowym/bębnem wielkim. Dodatkowo w co drugi beat wpleciony jest werbel, a pmiędzy uderzeniami bębna wybrzmiewają otwarte talerze. Nadaje to utworowi dynamiki i taneczności. Mimo to przez przez powtarzalność perkusji można nałożyć na nią spokojniejsze instrumenty i osiągnąć bardziej spokojne doznanie np. w deep house czy też fragmentach progresywnego houseu. W takiej sytuacji często używa się także elementów muzyki "soul". Jest też druga strona Housea ze swoimi bardziej dynamicznymi odmianami takimi jak Electro House, French House, Bounce House. Istnieje także big room house którego celem jest po prostu brzmieć jak najgłośniej i wydawać się jak największy. Nie jest to najlepszy wybór do tańczenia ale może okazać się dobrym wyborem np. na duże festiwale. Natomiast większość pozostałych odmian houseu jest wręcz idealna na parkiet.
        </opis>
        <artysci>Alan_Walker Daft_Punk deadmau5 Swedish_House_Mafia Owl_City</artysci>
      </gatunek>
      <gatunek taneczny="nie" nazwa="Hip-Hop/rap">
        <artysci>Kendrick_Lamar Eminem Drake</artysci>
        <opis>
